name: shopo-bober

services:
  shop-db:
    image: postgres:17.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $SHOP_DB_USERNAME -d $SHOP_DB_NAME" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=$SHOP_DB_NAME
      - POSTGRES_USER=$SHOP_DB_USERNAME
      - POSTGRES_PASSWORD=$SHOP_DB_PASSWORD
    ports:
      - ${SHOP_DB_PORT}:5432

  shop-service:
    build:
      context: ./ShopService
      dockerfile: ./Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shop-db:5432/$SHOP_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$SHOP_DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$SHOP_DB_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=$HIBERNATE_DDL_MODE
    depends_on:
      shop-db:
        condition: service_healthy
    ports:
      - $SHOP_SERVICE_PORT:8080



